name: Fail Job with Notification

on:
  push:
    branches:
      - main

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Force failure
        run: |
          echo "Simulating failure..."
          exit 1
        continue-on-error: true
        id: failure-step

      - name: Capture logs
        if: failure()
        run: |
          echo "Capturing logs from failure..."
          LOGS=$(tail -n 50 /var/log/syslog)
          echo "Logs: $LOGS"
          echo "::set-output name=logs::$LOGS"
        id: capture-logs

  failure-notification:
    runs-on: ubuntu-latest
    needs: fail-job
    if: failure()
    steps:
      - name: Send failure notification to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"GitHub Action failed in fail-job. Logs: ${{ needs.fail-job.outputs.logs }}\"}" \
          https://webhooksource-kubiya.hooks.kubiya.ai:8443/NFg08dN_1RNBZ-MP4M5fClwTEuCcyFoDttLQTj8xgOnSCbtqLPhuVfHkWnvXiKXlroILiWVL237h2yuyBeg7KA==
