name: Fail Job with Notification

on:
  push:
    branches:
      - main  # This will trigger on pushes to the main branch

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Force failure
        run: |
          echo "This is going to fail"
          exit 1  # Exiting with a non-zero status code to force failure

  failure-notification:
    runs-on: ubuntu-latest
    needs: fail-job  # This ensures that this job only runs after 'fail-job'
    if: failure()    # Runs only if the 'fail-job' fails
    steps:
      - name: Send failure notification to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\":\"GitHub Action failed in fail-job\"}" \
          https://webhooksource-kubiya.hooks.kubiya.ai:8443/NFg08dN_1RNBZ-MP4M5fClwTEuCcyFoDttLQTj8xgOnSCbtqLPhuVfHkWnvXiKXlroILiWVL237h2yuyBeg7KA==
