name: Fail Job with Notification

on:
  push:
    branches:
      - main

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Force failure
        run: |
          echo "This is going to fail"
          exit 1  # Exiting with a non-zero status code to force failure

      - name: Capture logs on failure
        if: failure()
        run: |
          echo "Capturing failure logs..."
          LOGS=$(tail -n 100 $GITHUB_WORKSPACE)
          echo "::set-output name=logs::$LOGS"
        id: capture-logs

  failure-notification:
    runs-on: ubuntu-latest
    needs: fail-job
    if: failure()
    steps:
      - name: Send failure notification to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\":\"GitHub Action failed in fail-job. Logs: ${{ needs.fail-job.outputs.logs }}\"}" \
          https://webhooksource-kubiya.hooks.kubiya.ai:8443/NFg08dN_1RNBZ-MP4M5fClwTEuCcyFoDttLQTj8xgOnSCbtqLPhuVfHkWnvXiKXlroILiWVL237h2yuyBeg7KA==
